import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import AppAsyncComponent from "@/components/AppAsyncComponent";

const inter = Inter({ subsets: ["latin"] });

const Component = AppAsyncComponent(() => import("../modules/MainPage/index"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Flight Search Application</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Component />
      </main>
    </>
  );
}
